language: node_js
node_js:
  - "0.8"
  - "0.9"
branches:
  only:
    - master
before_script:
  - git clone git://github.com/visionmedia/node-jscoverage.git
  - cd node-jscoverage
  - ./configure
  - make
  - cd ..
